services:
  app:
    build:
      context: .
      args: { APP_ENV: dev }
    container_name: worktimeflow_dev
    ports:
      - "8081:80"                 # visit http://localhost:8081
    environment:
      APP_ENV: dev
      SERVER_NAME: ":80"          # accept any host locally
      CADDY_GLOBAL_OPTIONS: "auto_https off"
      HOME: /tmp
      COMPOSER_HOME: /tmp/composer
      COMPOSER_CACHE_DIR: /tmp/composer/cach
    volumes:
      - ./:/app                   # bind entire project (includes vendor on host)
      - dev_var:/app/var          # keep cache/logs out of your repo
      - ./Caddyfile:/etc/frankenphp/Caddyfile:ro
    depends_on:
      database:
        condition: service_healthy
    tty: true
    user: "0:0"
    entrypoint: ["/bin/sh","-lc","/app/docker/entrypoint.sh"]

  database:
    image: mariadb:10.11.2
    container_name: wtf_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "3307:3306"               # optional host access
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  dev_var:
  mariadb_data:
