<?php
namespace App\Service\Terminal\Admin;

use App\Entity\User;
use App\Repository\UserRepository;
use App\Service\Terminal\ArgsParser;
use App\Service\Terminal\TerminalStateService;
use Doctrine\ORM\EntityManagerInterface;
use Random\RandomException;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

/**
 * All user-related terminal commands live here.
 * TerminalService routes here for commands starting with "users:".
 */
final class UserTerminalService
{
    private const WZ_ADD = 'users:add';

    /**
     * Sequence of prompts for the interactive "users:add" wizard.
     * Each step accepts empty as "null", except email (required).
     */
    private const ADD_STEPS = [
        [
            'key'     => 'email',
            'label'   => "New user's email? (required)",
            'example' => 'alice@example.com',
        ],
        [
            'key'     => 'username',
            'label'   => 'Username? (Enter to derive from email)',
            'example' => 'Alice',
        ],
        [
            'key'     => 'roles',
            'label'   => 'Roles? (comma-separated; Enter for ROLE_USER)',
            'example' => 'ROLE_USER, ROLE_ADMIN',
        ],
        [
            'key'     => 'password',
            'label'   => 'Password? (Enter for autogenerated)',
            'example' => 'S3cur3Passw0rd',
        ],
        [
            'key'     => 'notify',
            'label'   => 'Send credentials email? (yes/no, Enter = yes)',
            'example' => 'yes',
        ],
    ];

    public function __construct(
        private UserRepository $users,
        private EntityManagerInterface $em,
        private UserPasswordHasherInterface $hasher,
        private MailerInterface $mailer,
        private UrlGeneratorInterface $urls,
        private Security $security,
        private TerminalStateService $wiz,
    ) {}

    /**
     * users:list [limit] [--q=search] [--is-active=active|inactive|all]
     *
     * Examples:
     *  - users:list
     *  - users:list 25
     *  - users:list --q=anna
     *  - users:list --is-active=inactive
     *
     * Returns a Twig view to match the admin terminal UI.
     *
     * @param array<int,string> $tokens
     * @return array{view?:string, vars?:array, output?:string, success:bool}
     */
    public function listCommand(array $tokens): array
    {
        ['args' => $args, 'flags' => $flags] = ArgsParser::parse($tokens);

        $limit = (isset($args[0]) && ctype_digit($args[0])) ? (int) $args[0] : 50;
        $limit = max(1, min(100, $limit));

        $q          = isset($flags['q']) ? (string) $flags['q'] : null;
        $rawFlag    = $flags['is-active'] ?? null;
        $rawFlagStr = $rawFlag !== null ? strtolower((string) $rawFlag) : null;

        // Tri-state: true / false / null (no filter)
        $isActive = true; // default: active only
        if ($rawFlagStr !== null) {
            $truthy  = ['1', 'true', 'yes', 'y', 'on', 'active'];
            $falsy   = ['0', 'false', 'no', 'n', 'off', 'inactive'];
            $neutral = ['all', '*', 'any'];
            if (in_array($rawFlagStr, $truthy, true)) {
                $isActive = true;
            } elseif (in_array($rawFlagStr, $falsy, true)) {
                $isActive = false;
            } elseif (in_array($rawFlagStr, $neutral, true)) {
                $isActive = null;
            }
        }

        // Expecting: id, email, username, roles(array), active(bool) from repo helper
        $rows = $this->users->fetchListRowsSearched($limit, $q, $isActive);

        $rows = array_map(static function (array $r): array {
            return [
                'id'       => (string) ($r['id'] ?? ''),
                'email'    => (string) ($r['email'] ?? ''),
                'username' => (string) ($r['username'] ?? ''),
                'roles'    => is_array($r['roles'] ?? null)
                    ? implode(', ', $r['roles'])
                    : (string) ($r['roles'] ?? ''),
                'active'   => array_key_exists('active', $r) ? (bool) $r['active'] : null,
            ];
        }, $rows ?? []);

        return [
            'view'    => 'terminal/admin/terminal_commands/_users_list_admin.html.twig',
            'vars'    => [
                'rows'         => $rows,
                'limit'        => $limit,
                'q'            => $q,
                'isActive'     => $isActive,
                'activeFlagRaw'=> $rawFlagStr,
            ],
            'success' => true,
        ];
    }

    /**
     * users:show <id|email|username>
     *
     * Examples:
     *  - users:show 3
     *  - users:show alice@example.com
     *  - users:show Alice
     *
     * @param array<int,string> $tokens
     * @return array{view?:string, vars?:array, output?:string, success:bool}
     */
    public function showCommand(array $tokens): array
    {
        if (count($tokens) !== 1) {
            return ['output' => 'Usage: users:show <id|email|username>', 'success' => false];
        }

        $key = (string) $tokens[0];
        $u   = $this->users->findOneByIdEmailOrUsername($key);

        if (!$u) {
            return ['output' => 'User not found.', 'success' => false];
        }

        return [
            'view'    => 'terminal/admin/terminal_commands/_users_show_admin.html.twig',
            'vars'    => ['user' => $u],
            'success' => true,
        ];
    }

    /**
     * users:add --email=... [--username=...] [--password=...] [--roles=ROLE_USER,ROLE_ADMIN]
     *
     * - If flags are provided, keeps the existing non-interactive behaviour.
     * - Without flags, starts an interactive multi-step wizard using the
     *   shared step-by-step Twig partial and ends with a summary Twig view.
     *
     * @param array<int,string> $tokens
     * @return array
     * @throws RandomException
     */
    public function addCommand(array $tokens): array
    {
        ['args' => $args, 'flags' => $f] = ArgsParser::parse($tokens);

        // If flags were supplied, keep non-interactive behavior for BC
        if (!empty($f)) {
            return $this->addCommandNonInteractive($f);
        }

        // Interactive wizard
        $userId = $this->currentUserKey();
        $this->wiz->set($userId, [
            'mode' => self::WZ_ADD,
            'step' => 0,
            'data' => [],
        ]);

        $s     = self::ADD_STEPS[0];
        $total = count(self::ADD_STEPS);

        return [
            'view'    => 'terminal/admin/terminal_commands/partials/_step-by-step_prompt.html.twig',
            'vars'    => [
                'label'   => $s['label'],
                'example' => $s['example'] ?? null,
                'step'    => 1,
                'total'   => $total,
            ],
            'success' => true,
            'await'   => true,
        ];
    }

    /**
     * Non-interactive "users:add" as you already had it.
     *
     * @param array<string,mixed> $f
     * @return array{output:string, success:bool}
     * @throws RandomException
     */
    private function addCommandNonInteractive(array $f): array
    {
        $email    = isset($f['email']) ? trim((string) $f['email']) : '';
        $username = isset($f['username']) ? trim((string) $f['username']) : (isset($f['name']) ? trim((string) $f['name']) : null);
        $password = isset($f['password']) ? (string) $f['password'] : null;
        $rolesStr = $f['roles'] ?? $f['role'] ?? null;

        if ($email === '') {
            return ['output' => 'Usage: users:add --email=alice@example.com [--username=Alice|--name=Alice] [--password=Pass123] [--roles=ROLE_USER,ROLE_ADMIN]', 'success' => false];
        }
        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            return ['output' => 'Invalid email format.', 'success' => false];
        }
        if ($this->users->findOneBy(['email' => $email])) {
            return ['output' => 'Email already exists.', 'success' => false];
        }

        if ($username === null || $username === '') {
            $local    = strstr($email, '@', true) ?: $email;
            $username = $local;
        }

        $roles = ['ROLE_USER'];
        if ($rolesStr !== null && $rolesStr !== '') {
            $roles = $this->normalizeRoles((string) $rolesStr) ?: ['ROLE_USER'];
        }

        $plain = $password ?: bin2hex(random_bytes(4)); // 8 hex chars

        $user = new User();
        $user->setEmail($email);
        $user->setUsername($username);
        $user->setRoles($roles);
        $user->setPassword($this->hasher->hashPassword($user, $plain));

        try {
            $this->em->persist($user);
            $this->em->flush();
        } catch (\Throwable $e) {
            return ['output' => 'Failed to create user: ' . $e->getMessage(), 'success' => false];
        }

        $loginUrl = $this->urls->generate('app_login', [], UrlGeneratorInterface::ABSOLUTE_URL);
        $emailMsg = (new TemplatedEmail())
            ->from('no-reply@worktimeflow.local')
            ->to($user->getEmail())
            ->subject('Your WORKTIMEFLOW account')
            ->htmlTemplate('admin/emails/user_created.html.twig')
            ->context([
                'username'   => (string) $user->getUsername(),
                'user_email' => (string) $user->getEmail(),
                'password'   => $plain,
                'login_url'  => $loginUrl,
            ]);

        $sent = false;
        try {
            $this->mailer->send($emailMsg);
            $sent = true;
        } catch (\Throwable $e) {
            // swallow, we only report below
        }

        $msg = sprintf(
            'User created: id=%d, email=%s, username=%s, roles=%s. %s',
            $user->getId(),
            $user->getEmail(),
            $user->getUsername(),
            implode(',', $user->getRoles()),
            $sent ? 'Email sent.' : 'Email failed to send.'
        );

        return ['output' => $msg, 'success' => true];
    }

    /**
     * Handle interactive input if a wizard is active for the current admin.
     * Called by TerminalService *before* normal command parsing.
     */
    public function handleInteractive(string $rawInput): ?array
    {
        $userId = $this->currentUserKey();
        $state  = $this->wiz->get($userId);
        if (!$state) {
            return null; // no wizard active
        }

        $t = trim($rawInput);

        // Allow restarting the wizard while inside it
        if ($t === 'users:add' || $t === 'u.a') {
            $this->wiz->set($userId, [
                'mode' => self::WZ_ADD,
                'step' => 0,
                'data' => [],
            ]);

            $s     = self::ADD_STEPS[0];
            $total = count(self::ADD_STEPS);

            return [
                'view'    => 'terminal/admin/terminal_commands/partials/_step-by-step_prompt.html.twig',
                'vars'    => [
                    'label'   => $s['label'],
                    'example' => $s['example'] ?? null,
                    'step'    => 1,
                    'total'   => $total,
                ],
                'success' => true,
                'await'   => true,
            ];
        }

        // Allow cancel
        if ($t === 'cancel') {
            $this->wiz->clear($userId);
            return ['output' => 'Canceled.', 'success' => true];
        }

        // Continue wizard based on mode
        return match ($state['mode'] ?? null) {
            self::WZ_ADD => $this->handleAddStep($state, $t, $userId),
            default      => null,
        };
    }

    /**
     * Internal step handler for the "users:add" wizard.
     *
     * @throws RandomException
     */
    private function handleAddStep(array $state, string $rawInput, string $userId): array
    {
        $i     = (int) ($state['step'] ?? 0);
        $steps = self::ADD_STEPS;

        // Save previous answer with per-field rules
        if ($i < count($steps)) {
            $key = $steps[$i]['key'];
            $val = $rawInput;

            if ($key === 'email') {
                if ($val === '' || !filter_var($val, FILTER_VALIDATE_EMAIL)) {
                    // re-ask same step with error message
                    $s     = $steps[$i];
                    $total = count($steps);

                    return [
                        'view'    => 'terminal/admin/terminal_commands/partials/_step-by-step_prompt.html.twig',
                        'vars'    => [
                            'label'   => "Please enter a valid email (e.g., alice@example.com).",
                            'example' => $s['example'] ?? null,
                            'step'    => $i + 1,
                            'total'   => $total,
                        ],
                        'success' => false,
                        'await'   => true,
                    ];
                }
                if ($this->users->findOneBy(['email' => $val])) {
                    $s     = $steps[$i];
                    $total = count($steps);

                    return [
                        'view'    => 'terminal/admin/terminal_commands/partials/_step-by-step_prompt.html.twig',
                        'vars'    => [
                            'label'   => "Email already exists. Enter a different email.",
                            'example' => $s['example'] ?? null,
                            'step'    => $i + 1,
                            'total'   => $total,
                        ],
                        'success' => false,
                        'await'   => true,
                    ];
                }
            }

            $state['data'][$key] = ($val === '') ? null : $val;
            $i++;
        }

        // More questions remaining?
        if ($i < count($steps)) {
            $state['step'] = $i;
            $this->wiz->set($userId, $state);

            $s     = $steps[$i];
            $total = count($steps);

            return [
                'view'    => 'terminal/admin/terminal_commands/partials/_step-by-step_prompt.html.twig',
                'vars'    => [
                    'label'   => $s['label'],
                    'example' => $s['example'] ?? null,
                    'step'    => $i + 1, // 0-based -> human step
                    'total'   => $total,
                ],
                'success' => true,
                'await'   => true,
            ];
        }

        // --- All answers collected: create the user
        $d      = $state['data'] ?? [];
        $email  = (string) ($d['email'] ?? '');
        $username = $d['username'] ?? null;
        if ($username === null || $username === '') {
            $username = strstr($email, '@', true) ?: $email;
        }

        $roles = ['ROLE_USER'];
        if (!empty($d['roles'])) {
            $norm = $this->normalizeRoles((string) $d['roles']);
            if ($norm) {
                $roles = $norm;
            }
        }

        $plain = !empty($d['password'])
            ? (string) $d['password']
            : bin2hex(random_bytes(4));

        $notify = true;
        if (array_key_exists('notify', $d) && $d['notify'] !== null) {
            $ans    = strtolower((string) $d['notify']);
            $notify = !in_array($ans, ['no', 'n', '0', 'false', 'off'], true);
        }

        $user = new User();
        $user->setEmail($email);
        $user->setUsername($username);
        $user->setRoles($roles);
        $user->setPassword($this->hasher->hashPassword($user, $plain));

        try {
            $this->em->persist($user);
            $this->em->flush();
        } catch (\Throwable $e) {
            $this->wiz->clear($userId);
            return ['output' => 'Failed to create user: ' . $e->getMessage(), 'success' => false];
        }

        $sent = false;
        if ($notify) {
            try {
                $loginUrl = $this->urls->generate('app_login', [], UrlGeneratorInterface::ABSOLUTE_URL);
                $emailMsg = (new TemplatedEmail())
                    ->from('no-reply@worktimeflow.local')
                    ->to($user->getEmail())
                    ->subject('Your WORKTIMEFLOW account')
                    ->htmlTemplate('admin/emails/user_created.html.twig')
                    ->context([
                        'username'   => (string) $user->getUsername(),
                        'user_email' => (string) $user->getEmail(),
                        'password'   => $plain,
                        'login_url'  => $loginUrl,
                    ]);
                $this->mailer->send($emailMsg);
                $sent = true;
            } catch (\Throwable $e) {
                // ignore; just mark as not sent
            }
        }

        // Clear wizard state
        $this->wiz->clear($userId);

        // Render summary via Twig (no plaintext password)
        return [
            'view'    => 'terminal/admin/terminal_commands/_users_created_summary.html.twig',
            'vars'    => [
                'id'            => $user->getId(),
                'username'      => $user->getUsername(),
                'email'         => $user->getEmail(),
                'roles'         => implode(',', $user->getRoles()),
                'passwordLabel' => !empty($d['password']) ? '(set)' : '(autogenerated)',
                'notifyLabel'   => $sent ? 'sent' : 'not sent',
            ],
            'success' => true,
        ];
    }

    private function currentUserKey(): string
    {
        $u = $this->security->getUser();
        return method_exists($u, 'getUserIdentifier')
            ? (string) $u->getUserIdentifier()
            : 'guest';
    }

    /**
     * users:update <id|email> [--email=...] [--username=...] [--roles=ROLE_X,ROLE_Y]
     * - No password change here.
     * - Email must be valid + unique (if changed).
     * - Roles replace the entire set (normalized to ROLE_*). If omitted, roles unchanged.
     */
    public function updateCommand(array $tokens): array
    {
        ['args' => $args, 'flags' => $f] = ArgsParser::parse($tokens);
        $target   = $args[0] ?? '';
        $newEmail = isset($f['emails']) ? trim((string) $f['emails']) : null;
        $username = isset($f['username']) ? trim((string) $f['username']) : null;
        $rolesStr = $f['roles'] ?? $f['role'] ?? null;

        if ($target === '') {
            return ['output' => 'Usage: users:update <id|email> [--email=..] [--username=..] [--roles=ROLE_X,ROLE_Y]', 'success' => false];
        }

        $user = $this->users->findOneByIdOrEmailInsensitive($target);
        if (!$user) {
            return ['output' => 'User not found (by id/emails).', 'success' => false];
        }

        $changed = [];

        // Email update (validate + unique)
        if ($newEmail !== null) {
            if (!filter_var($newEmail, FILTER_VALIDATE_EMAIL)) {
                return ['output' => 'Invalid emails format.', 'success' => false];
            }
            $existing = $this->users->findOneBy(['email' => $newEmail]);
            if ($existing && $existing->getId() !== $user->getId()) {
                return ['output' => 'Email already in use by another account.', 'success' => false];
            }
            $user->setEmail($newEmail);
            $changed[] = 'email';
        }

        // Username update
        if ($username !== null) {
            $user->setUsername($username);
            $changed[] = 'username';
        }

        // Roles update (replace entire set if provided)
        if ($rolesStr !== null && $rolesStr !== '') {
            $roles = $this->normalizeRoles((string) $rolesStr);
            if (!$roles) {
                return ['output' => 'No valid roles provided.', 'success' => false];
            }
            $user->setRoles($roles);
            $changed[] = 'roles';
        }

        if (!$changed) {
            return ['output' => 'Nothing to update. Provide at least one of --emails, --username, --roles.', 'success' => false];
        }

        try {
            $this->em->flush();
        } catch (\Throwable $e) {
            return ['output' => 'Failed to update user: ' . $e->getMessage(), 'success' => false];
        }

        return [
            'output'  => sprintf(
                'Updated user id=%d (%s). Changed: %s',
                $user->getId(),
                $user->getEmail(),
                implode(', ', $changed)
            ),
            'success' => true,
        ];
    }

    /**
     * users:forgot-password <id|email>
     * - Generates a new temporary password, sets it, emails the user.
     * - Terminal does NOT print the password back.
     */
    public function forgotPasswordCommand(array $tokens): array
    {
        ['args' => $args] = ArgsParser::parse($tokens);
        $target = $args[0] ?? '';
        if ($target === '') {
            return ['output' => 'Usage: users:forgot-password <id|email>', 'success' => false];
        }

        $user = $this->users->findOneByIdOrEmailInsensitive($target);
        if (!$user) {
            return ['output' => 'User not found (by id/emails).', 'success' => false];
        }

        $temp = bin2hex(random_bytes(4));
        $user->setPassword($this->hasher->hashPassword($user, $temp));

        try {
            $this->em->flush();
        } catch (\Throwable $e) {
            return ['output' => 'Failed to reset password: ' . $e->getMessage(), 'success' => false];
        }

        $loginUrl = $this->urls->generate('app_login', [], UrlGeneratorInterface::ABSOLUTE_URL);

        $emailMsg = (new TemplatedEmail())
            ->from('no-reply@worktimeflow.local')
            ->to($user->getEmail())
            ->subject('WORKTIMEFLOW — Password reset')
            ->htmlTemplate('admin/emails/password_reset.html.twig')
            ->context([
                'username'   => (string) $user->getUsername(),
                'user_email' => (string) $user->getEmail(),
                'password'   => $temp,
                'login_url'  => $loginUrl,
            ]);

        $sent = false;
        try {
            $this->mailer->send($emailMsg);
            $sent = true;
        } catch (\Throwable $e) {
            // swallow and report
        }

        return [
            'output'  => sprintf(
                'Temporary password set for id=%d (%s). %s',
                $user->getId(),
                $user->getEmail(),
                $sent ? 'Email sent.' : 'Email failed to send.'
            ),
            'success' => true,
        ];
    }

    /**
     * users:delete <id|email> [--force]
     *
     * - Resolves a user by numeric id or case-insensitive email.
     * - Detaches teams (ManyToMany).
     * - Detaches timelogs by setting Timelog.user = null.
     * - If related records exist and --force is NOT provided, returns a warning and does nothing.
     */
    public function deleteCommand(array $tokens): array
    {
        ['args' => $args, 'flags' => $flags] = ArgsParser::parse($tokens);

        $target = $args[0] ?? '';
        if ($target === '') {
            return ['output' => 'Usage: users:delete <id|email> [--force]', 'success' => false];
        }

        $user = $this->users->findOneByIdOrEmailInsensitive($target);
        if (!$user) {
            return ['output' => 'User not found (by id/email).', 'success' => false];
        }

        // Self-protection: don’t allow deleting yourself
        if ($this->security->getUser() instanceof \Symfony\Component\Security\Core\User\UserInterface) {
            $me = $this->security->getUser();
            if (method_exists($me, 'getId') && $user->getId() === $me->getId()) {
                return ['output' => 'Refusing to delete the currently logged-in account.', 'success' => false];
            }
        }

        $teamsCount    = $user->getTeams()->count();
        $timelogsCount = $user->getTimelogs()->count();
        $hasRelations  = ($teamsCount > 0) || ($timelogsCount > 0);

        $force = isset($flags['force']) && $flags['force'] !== false;

        if ($hasRelations && !$force) {
            return [
                'output'  => sprintf(
                    'Refusing to delete. Found %d team link(s) and %d timelog(s). Re-run with --force to detach and delete.',
                    $teamsCount,
                    $timelogsCount
                ),
                'success' => false,
            ];
        }

        $detachedTeams = 0;
        foreach ($user->getTeams() as $team) {
            $user->removeTeam($team);
            $detachedTeams++;
        }

        $detachedLogs = 0;
        foreach ($user->getTimelogs() as $log) {
            $log->setUser(null);
            $detachedLogs++;
        }

        $id    = $user->getId();
        $email = (string) $user->getEmail();

        try {
            $this->em->remove($user);
            $this->em->flush();
        } catch (\Throwable $e) {
            return ['output' => 'Failed to delete user: ' . $e->getMessage(), 'success' => false];
        }

        return [
            'output'  => sprintf(
                'Deleted user id=%d (%s). Detached %d team link(s), %d timelog(s).',
                $id,
                $email,
                $detachedTeams,
                $detachedLogs
            ),
            'success' => true,
        ];
    }

    /** Normalize comma-separated roles to ROLE_* and dedup. */
    private function normalizeRoles(string $rolesCsv): array
    {
        $parts = array_map('trim', explode(',', $rolesCsv));
        $norm  = array_map(
            static fn (string $r) => str_starts_with($r = strtoupper($r), 'ROLE_') ? $r : ('ROLE_' . $r),
            $parts
        );

        $norm = array_values(array_unique(array_filter($norm)));
        return $norm;
    }

    public function deactivateCommand(array $tokens): array
    {
        ['args' => $args] = ArgsParser::parse($tokens);
        $target = $args[0] ?? '';
        if ($target === '') {
            return ['output' => 'Usage: users:deactivate <id|email>', 'success' => false];
        }

        $user = $this->users->findOneByIdOrEmailInsensitive($target);
        if (!$user) {
            return ['output' => 'User not found (by id/email).', 'success' => false];
        }

        if (method_exists($this->security->getUser(), 'getId')
            && $this->security->getUser()?->getId() === $user->getId()
        ) {
            return ['output' => 'Refusing to deactivate the currently logged-in account.', 'success' => false];
        }

        $user->setIsActive(false);
        try {
            $this->em->flush();
        } catch (\Throwable $e) {
            return ['output' => 'Failed to deactivate user: ' . $e->getMessage(), 'success' => false];
        }

        return [
            'output'  => sprintf(
                'User id=%d (%s) deactivated.',
                $user->getId(),
                $user->getEmail()
            ),
            'success' => true,
        ];
    }

    public function activateCommand(array $tokens): array
    {
        ['args' => $args] = ArgsParser::parse($tokens);
        $target = $args[0] ?? '';
        if ($target === '') {
            return ['output' => 'Usage: users:activate <id|email>', 'success' => false];
        }

        $user = $this->users->findOneByIdOrEmailInsensitive($target);
        if (!$user) {
            return ['output' => 'User not found (by id/email).', 'success' => false];
        }

        $user->setIsActive(true);
        try {
            $this->em->flush();
        } catch (\Throwable $e) {
            return ['output' => 'Failed to activate user: ' . $e->getMessage(), 'success' => false];
        }

        return [
            'output'  => sprintf(
                'User id=%d (%s) activated.',
                $user->getId(),
                $user->getEmail()
            ),
            'success' => true,
        ];
    }

    /**
     * Optional: profile-side commands (non-admin) can still live here.
     * TerminalService calls this when routing a *user* (non-admin) request.
     */
    public function handle(string $input): array
    {
        return match ($input) {
            'help' => ['output' => 'Available (user): ping', 'success' => true],
            'ping' => ['output' => 'pong (user)', 'success' => true],
            default => ['output' => 'Unhandled user command', 'success' => false],
        };
    }
}
