name: Review

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.11.2
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: db
          MYSQL_USER: db_user
          MYSQL_PASSWORD: db_password
        ports:
          - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: ctype, iconv, pdo_mysql
          tools: composer:v2

      - name: Check PHP version
        run: php -v

      - name: Check Composer version
        run: composer -V

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Start Docker services
        run: docker-compose up -d

      - name: Wait for database to be ready
        run: |
          until docker exec mariadb_container mysqladmin ping -h "127.0.0.1" --silent; do
            echo "Waiting for MariaDB..."
            sleep 2
          done

      - name: Run Symfony console commands
        run: |
          php bin/console cache:clear
          php bin/console doctrine:migrations:migrate --no-interaction

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit

  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate changelog
        uses: metcalfc/changelog-generator@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Post changelog as PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: "### Changelog\n${{ steps.changelog.outputs.changelog }}"
