name: CI/CD for Symfony

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.11.2
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: db
          MYSQL_USER: db_user
          MYSQL_PASSWORD: db_password
        ports:
          - "0:3306"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: ctype, iconv, pdo_mysql
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Start Docker services
        run: docker compose up -d

      - name: Run Symfony console commands
        run: |
          php bin/console cache:clear
          if php bin/console doctrine:migrations:status | grep -q "Available Migrations"; then
            php bin/console doctrine:migrations:migrate --no-interaction
          else
            echo "No migrations found, skipping."
          fi

      - name: Run PHPUnit tests
        env:
          DATABASE_URL: "mysql://db_user:db_password@127.0.0.1:3306/db"
        run: vendor/bin/phpunit

  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Changelog
        uses: release-drafter/release-drafter@v5
        id: changelog
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Format Changelog as Keep a Changelog
        run: |
          echo "# Changelog\n\nAll notable changes to this project will be documented in this file.\n" > formatted_changelog.md
          echo "The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/)," >> formatted_changelog.md
          echo "and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n" >> formatted_changelog.md
          echo "## [Unreleased]\n" >> formatted_changelog.md
          echo "${{ steps.changelog.outputs.changelog }}" >> formatted_changelog.md

      - name: Post Changelog as PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: "${{ steps.changelog.outputs.changelog }}"
